
##Dynakube.yaml should be downloaded in dynatrace after generating Dynatrace Token and Data ingest token in Kubernetes page while connecting the EKS cluster



apiVersion: v1
data:
  apiToken: ZHxxxxxxxxxxx
  dataIngestToken: ZHxxxxxxxxxxx
kind: Secret
metadata:
  name: eks-aws-k86-demo-client
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: eks-aws-k86-demo-client
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://ywf15506.live.dynatrace.com/api
  tokens: eks-aws-k86-demo-client
  activeGate:
    capabilities:
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 200m
        memory: 6Gi
      limits:
        cpu: 1000m
        memory: 6Gi
    replicas: 1
  kspm:
    mappedHostPaths:
      - /boot
      - /etc
      - /proc/sys/kernel
      - /sys/fs
      - /sys/kernel/security/apparmor
      - /usr/lib/systemd/system
      - /var/lib
  templates:
    kspmNodeConfigurationCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-k8s-node-config-collector
        tag: 1.5.10
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: eks-aws-k86-demo-client-agents
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://ywf15506.live.dynatrace.com/api
  tokens: eks-aws-k86-demo-client
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - debugging
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    replicas: 3
  templates:
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
  logMonitoring: {}
  telemetryIngest:
    protocols:
      - jaeger
      - otlp
      - statsd
      - zipkin
    serviceName: telemetry-ingest
